### ISSUE TITLE
Criação da aplicação Azure e da tabela

### ISSUE THREAD

**Issue by marcosv2017** [jeffersonkr/devops-ac06#13]

**Comment by marcosv2017** [comment]
O dono do repositório deverá:
a) Acessar o seu portal Azure e criar uma nova aplicação web (Web App) com o nome devopsac06usuarioGithub (por exemplo, se o seu usuário no GitHub for mmxabc, o nome deverá ser
devopsac06mmxabc).

b) Acessar a página de gerenciamento do MySQL inapp.
c) Criar a tabela app_curso:
CREATE TABLE `app_curso`
(`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
`nome` varchar(200) NOT NULL,
`periodo` varchar(50) NOT NULL,
`instituicao` varchar(200) NOT NULL);
d) Inserir alguns registros na tabela.

**Comment by raffaell95** [comment]
Banco de dados criado com sucesso!
